server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: usuario-service
          uri: lb://usuario-service
          predicates:
            - Path=//usuario/**
        - id: departamento-service
          uri: lb://departamento-service
          predicates:
            - Path=//departamento/**
        - id: casa-service
          uri: lb://casa-service
          predicates:
            - Path=//casa/**
