server:
  port: 8081
spring:
  cloud: 
    config:
      server:
        git:
          default-label: gateway
          uri: https://github.com/Th3Amiguit0/SD
          search-paths: config-data
  aplication:
    name: config-service
